workflow:
    rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

image: fedora:39

meson-build:
    script:
    - dnf -y install dnf-plugins-core
    - dnf -y groupinstall buildsys-build
    - dnf -y builddep pixman
    - dnf -y install meson
    - meson setup build
    - ninja -C build test
