name: Build External Project

on:
  workflow_dispatch:

jobs:
  build-external-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout external repository
      uses: actions/checkout@v2
      with:
        repository: 'https://github.com/Cateners/tiny_computer'  
        path: external-project  # 可选：指定一个子目录来检出项目

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: '3.3.0'  # 确保使用正确的 Flutter 版本

    - name: Install dependencies
      run: |
        cd external-project  # 如果你在上一步中指定了子目录
        flutter pub get

    - name: Build APK
      run: |
        cd external-project  # 如果你在上一步中指定了子目录
        flutter clean
        flutter build apk --target-platform android-arm64

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v3
      with:
        name: example-project-apk
        path: external-project/build/app/outputs/flutter-apk/app-arm64-release.apk
